export const ROUTES = {
  main: "/",
  login: "/login",
  registration: "/registration",
  events: "/events",
  projects: "/projects",
  profile: "/profile",
  logout: "/logout",
  users: "/users",
  createProject: "/projects/create",
  adminPanel: "/admin_panel",
  adminPanelUsers: "/admin-panel/users",
  adminPanelEvents: "/admin-panel/events",
  adminPanelProjects: "/admin-panel/projects",
};
